export const portfolioImages = {
  "LI-In-Bug.png": require("../../assets/portfolio/LI-In-Bug.png"),
  "Logo.png": require("../../assets/portfolio/Logo.png"),
  "agora.svg": require("../../assets/portfolio/agora.svg"),
  "android.svg": require("../../assets/portfolio/android.svg"),
  "apple.svg": require("../../assets/portfolio/apple.svg"),
  "atlas.webp": require("../../assets/portfolio/atlas.webp"),
  "atx-dao.png": require("../../assets/portfolio/atx-dao.png"),
  "bartynder.svg": require("../../assets/portfolio/bartynder.svg"),
  "base-logo-in-blue.png": require("../../assets/portfolio/base-logo-in-blue.png"),
  "bg.svg": require("../../assets/portfolio/bg.svg"),
  "bill-2.avif": require("../../assets/portfolio/bill-2.avif"),
  "bill-2.webp": require("../../assets/portfolio/bill-2.webp"),
  "bill.webp": require("../../assets/portfolio/bill.webp"),
  "bluebell.svg": require("../../assets/portfolio/bluebell.svg"),
  "bstw.png": require("../../assets/portfolio/bstw.png"),
  "buidlguidlDemoDay.png": require("../../assets/portfolio/buidlguidlDemoDay.png"),
  "buidlguidllogo.jpg": require("../../assets/portfolio/buidlguidllogo.jpg"),
  "callbacks.png": require("../../assets/portfolio/callbacks.png"),
  "carstarz.png": require("../../assets/portfolio/carstarz.png"),
  "coa.png": require("../../assets/portfolio/coa.png"),
  "cookie.png": require("../../assets/portfolio/cookie.png"),
  "curios.jpg": require("../../assets/portfolio/curios.jpg"),
  "dao-coalition.png": require("../../assets/portfolio/dao-coalition.png"),
  "dd.png": require("../../assets/portfolio/dd.png"),
  "discord-white-icon.svg": require("../../assets/portfolio/discord-white-icon.svg"),
  "disgo.webp": require("../../assets/portfolio/disgo.webp"),
  "eliza_banner.jpg": require("../../assets/portfolio/eliza_banner.jpg"),
  "email.svg": require("../../assets/portfolio/email.svg"),
  "engagementdotvision.png": require("../../assets/portfolio/engagementdotvision.png"),
  "etherscan.svg": require("../../assets/portfolio/etherscan.svg"),
  "faith.png": require("../../assets/portfolio/faith.png"),
  "filecoin-talk.png": require("../../assets/portfolio/filecoin-talk.png"),
  "github.svg": require("../../assets/portfolio/github.svg"),
  "gorglok.png": require("../../assets/portfolio/gorglok.png"),
  "hats.jpg": require("../../assets/portfolio/hats.jpg"),
  "jake.webp": require("../../assets/portfolio/jake.webp"),
  "ladders.webp": require("../../assets/portfolio/ladders.webp"),
  "link.svg": require("../../assets/portfolio/link.svg"),
  "linkedin.png": require("../../assets/portfolio/linkedin.png"),
  "maxresdefault.jpg": require("../../assets/portfolio/maxresdefault.jpg"),
  "maxresdefault2.jpg": require("../../assets/portfolio/maxresdefault2.jpg"),
  "maxresdefault3.png": require("../../assets/portfolio/maxresdefault3.png"),
  "maxresdefault4.png": require("../../assets/portfolio/maxresdefault4.png"),
  "new-beginnings.png": require("../../assets/portfolio/new-beginnings.png"),
  "nounspace.svg": require("../../assets/portfolio/nounspace.svg"),
  "of.jpg": require("../../assets/portfolio/of.jpg"),
  "onslaught.png": require("../../assets/portfolio/onslaught.png"),
  "opensea.png": require("../../assets/portfolio/opensea.png"),
  "optimism-ethereum-op-logo.png": require("../../assets/portfolio/optimism-ethereum-op-logo.png"),
  "optimism-fractal.jpg": require("../../assets/portfolio/optimism-fractal.jpg"),
  "organization.png": require("../../assets/portfolio/organization.png"),
  "os.svg": require("../../assets/portfolio/os.svg"),
  "overlap-shapes.png": require("../../assets/portfolio/overlap-shapes.png"),
  "pandemic.png": require("../../assets/portfolio/pandemic.png"),
  "pizzapeople.webp": require("../../assets/portfolio/pizzapeople.webp"),
  "pms.webp": require("../../assets/portfolio/pms.webp"),
  "portfolio.png": require("../../assets/portfolio/portfolio.png"),
  "project-venkman.png": require("../../assets/portfolio/project-venkman.png"),
  "raycast-controller.png": require("../../assets/portfolio/raycast-controller.png"),
  "rg-icon.png": require("../../assets/portfolio/rg-icon.png"),
  "scroll.svg": require("../../assets/portfolio/scroll.svg"),
  "snapshot.png": require("../../assets/portfolio/snapshot.png"),
  "solidity-guild.png": require("../../assets/portfolio/solidity-guild.png"),
  "starterKit.png": require("../../assets/portfolio/starterKit.png"),
  "superchain-demo-day.png": require("../../assets/portfolio/superchain-demo-day.png"),
  "supercharged-vector2.png": require("../../assets/portfolio/supercharged-vector2.png"),
  "trash.png": require("../../assets/portfolio/trash.png"),
  "unlock.png": require("../../assets/portfolio/unlock.png"),
  "venue-manager.svg": require("../../assets/portfolio/venue-manager.svg"),
  "warpcast-icon.png": require("../../assets/portfolio/warpcast-icon.png"),
  "weedies.webp": require("../../assets/portfolio/weedies.webp"),
  "worldwidebottlecaptoken.png": require("../../assets/portfolio/worldwidebottlecaptoken.png"),
  "x-icon.svg": require("../../assets/portfolio/x-icon.svg"),
  "x.svg": require("../../assets/portfolio/x.svg"),
  "youtube_social_circle_red.png": require("../../assets/portfolio/youtube_social_circle_red.png"),
  "ziti.svg": require("../../assets/portfolio/ziti.svg"),
} as const;

export type PortfolioImageKey = keyof typeof portfolioImages;

export function portfolioImage(key?: string) {
  if (!key) return undefined;
  return portfolioImages[key as PortfolioImageKey];
}
